name: Deploy Godot Web Build to Itch.io

on:
  workflow_dispatch: 

env:
  GODOT_VERSION: 4.6-stable
  GODOT_EXECUTABLE_URL: https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_linux.x86_64.zip
  GODOT_TEMPLATES_URL: https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_export_templates.tpz
  EXPORT_TEMPLATE_DIR: 4.6.stable 

jobs:
  export-and-publish:
    name: Export to Web and Publish to Itch.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          lfs: true 

      - name: Download and Install Godot
        run: |
          echo "Downloading Godot Engine..."
          wget -q ${{ env.GODOT_EXECUTABLE_URL }} -O godot.zip
          unzip godot.zip
          sudo mv Godot_v*linux.x86_64 /usr/local/bin/godot
          sudo chmod +x /usr/local/bin/godot

      - name: Download and Install Export Templates
        run: |
          echo "Downloading Export Templates..."
          wget -q ${{ env.GODOT_TEMPLATES_URL }} -O templates.tpz
          unzip templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${{ env.EXPORT_TEMPLATE_DIR }}
          mv templates/* ~/.local/share/godot/export_templates/${{ env.EXPORT_TEMPLATE_DIR }}/

      - name: Import Godot Assets
        run: |
          echo "Importing assets for the first time (Godot 4 requires this before exporting)..."
          godot --headless --editor --quit || true
          echo "Second pass of importation (necessary for heavy audio in Godot 4)..."
          godot --headless --editor --quit || true

      - name: Export Web Build
        run: |
          echo "Exporting HTML5 version..."
          mkdir -p build_web
          godot --headless --export-release "Web" build_web/index.html

      - name: Zip Exported Files
        working-directory: build_web
        run: |
          echo "Compress files to Itch.io..."
          zip -r ../advad_web_build.zip .

      - name: Upload to Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-web-build
          path: advad_web_build.zip

      - name: Download and Install Butler (Itch.io CLI)
        run: |
          echo "Download and installing Butler..."
          wget -qO butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          sudo chmod +x butler
          sudo mv butler /usr/local/bin/butler

      - name: Deploy to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          echo "Deploy build to Itch.io with Butler..."
          butler push advad_web_build.zip ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME_ID }}:html
